# Discover Nightly

name: discover-nightly

on:
  pull_request:
    branches: [develop]
    types: [labeled]

defaults:
  run:
    shell: bash

jobs:
  run-discover-nightly:
    uses: GEOS-ESM/CI-workflows-test/.github/workflows/swell-workflow01.yml@main
